import TodoListContainer from '@/components/TodoListContainer';
import TodoListInput from '@/components/TodoListInput'
import TodoContextProvider from '@/context/TodoContext';
import Head from 'next/head'
import { useRef, useState } from 'react'
import { flushSync } from 'react-dom';



export default function Home() {
  const listElement = useRef<HTMLDivElement>(null)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-sky-700 to-sky-900 h-screen flex flex-col items-center justify-center">
        <TodoContextProvider listElement={listElement}>
          <TodoListInput  />
          <TodoListContainer listContainer={listElement}  />
        </TodoContextProvider>
      </main>
    </>
  )
}
